# Generated by Django 5.2.5 on 2025-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
