# Generated by Django 5.2.5 on 2025-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
