# Generated by Django 5.2.5 on 2025-09-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0005_news_view_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="view_count",
        ),
    ]
