# Generated by Django 5.2.5 on 2025-09-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0006_remove_news_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="body_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="body_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="body_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
